language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
env:
  - DJANGO=1.5.5
  - DJANGO=1.6.6
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=vies runtests.py
after_success:
  coveralls
